# Generated by Django 6.0 on 2026-04-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='vegetable',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='crops.vegetable'),
            preserve_default=False,
        ),
    ]
