# Generated by Django 6.0 on 2026-04-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_disease_vegetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='treatment',
        ),
    ]
